apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-data
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
