apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc-data
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
