apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: media
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.110
    path: /mnt/ClusterStorage/media
  persistentVolumeReclaimPolicy: Retain
