---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi