apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg-system
spec:
  instances: 3  # Number of PostgreSQL instances
  startDelay: 300
  stopDelay: 300
  replicationSlots:
    highAvailability:
      enabled: true
    updateInterval: 300
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  superuserSecret:
    name: superuser
  bootstrap:
    initdb:
      database: mealie
      owner: mealie
      secret:
        name: mealie-secret
  storage:
    size: 20Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
