---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: homeassistant
data:
  TZ: Europe/Brussels
  configuration.yaml: |
    http:
      ip_ban_enabled: true
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.50.0/24
        - 172.18.0.0/24
        - 192.168.50.80
        - 10.0.0.0/8
    sonos:
      media_player:
        hosts:
          192.168.10.109
    mobile_app:

    ####################################################
    #                                                  #
    #                  Groups                          #
    #                                                  #
    ####################################################
    # https://www.home-assistant.io/integrations/mobile_app/
    group: !include groups.yaml
    

    ####################################################
    #                                                  #
    #                  Automations                     #
    #                                                  #
    ####################################################
    # https://www.home-assistant.io/integrations/automation/
    automation: !include automations.yaml

    ####################################################
    #                                                  #
    #                  Scripts                         #
    #                                                  #
    ####################################################
    # https://www.home-assistant.io/integrations/script/
    script: !include scripts.yaml

    ####################################################
    #                                                  #
    #                   Scene                          #
    #                                                  #
    ####################################################
    # https://www.home-assistant.io/integrations/scene/
    scene: !include scenes.yaml

  groups.yaml: |

  automations.yaml: |

  scripts.yaml: |

  scenes.yaml: |
