---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: homeassistant
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    log_dest stdout

    allow_anonymous false
    password_file /mosquitto/config/passwd
    
    # MQTTS listener
    listener 8883
    protocol mqtt

    cafile /mosquitto/certs/ca.crt
    keyfile /mosquitto/certs/tls.key
    certfile /mosquitto/certs/tls.crt

    # WS Listener
    listener 9001
    protocol websockets

  passwd: |
    tigo:$7$101$TmUIPgQSH6WnAwym$8u5HRwC8OV9pkWRPD/y/XBsz8dpbPqKuaatm8QMn6iXjo8ciMOIrZjgkJm4ZxBNuHZPawVOrJi1tQRVmcjASng==

