---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: isbtv 
  name: isbtv-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi