---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: habitica
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: habitica
  name: mongo-conf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi 