
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-external
  namespace: rook-ceph-external # namespace:cluster
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/ceph
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 60s

