apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-pvc-config
  namespace: media
spec:
  storageClassName: longhorn  # Optional, depending on your storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi