apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: homeassistant
spec:
  storageClassName: longhorn
  resources:
      requests:
        storage: 10Gi
  accessModes:
  - ReadWriteMany
