apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-cert-config
  namespace: media
data:
  client.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGojCCBIqgAwIBAgIEDbZl9zANBgkqhkiG9w0BAQsFADB7MQswCQYDVQQGEwJS
    TzESMBAGA1UEBxMJQnVjaGFyZXN0MRgwFgYDVQQKEw9DeWJlckdob3N0IFMuQS4x
    GzAZBgNVBAMTEkN5YmVyR2hvc3QgUm9vdCBDQTEhMB8GCSqGSIb3DQEJARYSaW5m
    b0BjeWJlcmdob3N0LnJvMB4XDTI1MTAwNTEzMjM1NloXDTM1MTAwMzEzMjM1Nlow
    czELMAkGA1UEBhMCUk8xEjAQBgNVBAcMCUJ1Y2hhcmVzdDEYMBYGA1UECgwPQ3li
    ZXJHaG9zdCBTLkEuMRMwEQYDVQQDDApDUWhteDhhdFd4MSEwHwYJKoZIhvcNAQkB
    FhJpbmZvQGN5YmVyZ2hvc3Qucm8wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQDUgLQsHZTmFNxiZ1gsMfLvMzL/aVB2oidIesqzFNuHNWAGNsxwuoFu/3XK
    J7qgoqwrdWyYxV4AIh4mBXxEMj498ocnxf/rZBmSlR8Y1+VXfKWIuPSj0/ZHeMhX
    ROs41ZPoWBJZ/1cRyIljKLsz2Pc5WYD1DiptwoUE+CkrO3g2vPwNTEJClvlokrzu
    KR9Grfk4/qujAr7QmN8odb4HiMFEyrkYCnrdJaWIaQHPyAt8xVWsANdOsVsfpOSE
    QEcbiaDr8A6AfA0TQQJkbHVN8bINVtZd2Vt8qATREo35TUMeTmuzJRN9NzRTZ+z0
    tkKvV5Rpe+9ALLjDU6l9EZJ4AmF1ODre0VBnvXWmnsW02FWr9+UWQkeXXIli+OV0
    nE5or0sXFPjScXb4uTVVfU5HUEtcYGh/0yTzd+ryG6V2iNplHpBLgsxG8OhiqY0n
    iDFIpIzPnmt3ufLhu2axMt3BYmQ2HpnUo7C6M+gl45TcI/VqIKQSWbbXvCqXqcpH
    UP8mLEn5SIaMoLHYh/5qr9Sbknfu7dmRvF4V8k2j+voUrz0F9vLnUCbceDvi5cR4
    ehflGUW9/Gp5BBsb8NvRDqBrgjf/nHmMM4V2GebyIFYDJvz/jIeSoy9E1apxD0u/
    F+n0YlveXpxpESZr3+pKzGyc9woawcUWcm9CZJjaZxu8/IFUfwIDAQABo4IBNDCC
    ATAwCQYDVR0TBAIwADALBgNVHQ8EBAMCBaAwNAYJYIZIAYb4QgENBCcWJUN5YmVy
    R2hvc3QgR2VuZXJhdGVkIFVzZXIgQ2VydGlmaWNhdGUwEQYJYIZIAYb4QgEBBAQD
    AgeAMB0GA1UdDgQWBBQUI4lcZK0TKTBYyWy8gFwrbpH79jCBrQYDVR0jBIGlMIGi
    gBTq10rWD8d7mrON4Cgzl4e3iKf2JaF/pH0wezELMAkGA1UEBhMCUk8xEjAQBgNV
    BAcTCUJ1Y2hhcmVzdDEYMBYGA1UEChMPQ3liZXJHaG9zdCBTLkEuMRswGQYDVQQD
    ExJDeWJlckdob3N0IFJvb3QgQ0ExITAfBgkqhkiG9w0BCQEWEmluZm9AY3liZXJn
    aG9zdC5yb4IJAJxUG61mxDS7MA0GCSqGSIb3DQEBCwUAA4ICAQAt8NCMgwV3QtMg
    tC/vdb46NFQSmwvqGbSl3H3ETA0oHt7MAL4AL/r2ctodx2YpefItmUAJlQcN/WPT
    jd5iQMf8AnyI08bD+ZRwFuvfOXD0uB03na6/l6jQNNvy7OHnKJb7kKB7Np80/wZd
    phi9Iqvnm3eSoimXAWGTD6MAtaHlBpxK2/m5zKUP2OKabzOQLxkYRq1qwAOXgKtL
    li5QSxb8lwmUqqqtFvNpJtntTgLmIHZ7kfOF9zVCUCNkRJnFlhSNzEZ4A86M8LEZ
    Cn0QREqCz5SyBAR9eR93KAvd2Xhc9zHcOnwRaDC5slH9uOwURdyeQEqiEA3kb1I5
    8XuotsokMrKHTrWGFKpDYet38ta6DHtaXYnPf0PDmWlnXbQyxwnv6X5swpr08AH6
    aXTv7Nx7mnqJZqjyDKThtzGvM0gvc+85MMaxBxh3nPZNM3oNt3q9DgXPMoc/C7fL
    vZWr0It29bj2v8HqUgshyZqbAvacIsw+6Uzb95AWAOKYvUr8GF2z22WJHj9XqNIT
    SWNBRYv5knCNOvimLOJ/jOjd1+6Rv1v2IshZ+uvpp5GeYje1sdWnni5+TfEAHXOy
    kkHWrez+/dIwXY4eT8vQS3Uk2ZT7SQXJBVV/JWS7h1f9xnoatZIAdyo6QpElAsfT
    sdDYGU56ansacaPMzjQVvw5Ot+PvcA==
    -----END CERTIFICATE-----
  client.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDUgLQsHZTmFNxi
    Z1gsMfLvMzL/aVB2oidIesqzFNuHNWAGNsxwuoFu/3XKJ7qgoqwrdWyYxV4AIh4m
    BXxEMj498ocnxf/rZBmSlR8Y1+VXfKWIuPSj0/ZHeMhXROs41ZPoWBJZ/1cRyIlj
    KLsz2Pc5WYD1DiptwoUE+CkrO3g2vPwNTEJClvlokrzuKR9Grfk4/qujAr7QmN8o
    db4HiMFEyrkYCnrdJaWIaQHPyAt8xVWsANdOsVsfpOSEQEcbiaDr8A6AfA0TQQJk
    bHVN8bINVtZd2Vt8qATREo35TUMeTmuzJRN9NzRTZ+z0tkKvV5Rpe+9ALLjDU6l9
    EZJ4AmF1ODre0VBnvXWmnsW02FWr9+UWQkeXXIli+OV0nE5or0sXFPjScXb4uTVV
    fU5HUEtcYGh/0yTzd+ryG6V2iNplHpBLgsxG8OhiqY0niDFIpIzPnmt3ufLhu2ax
    Mt3BYmQ2HpnUo7C6M+gl45TcI/VqIKQSWbbXvCqXqcpHUP8mLEn5SIaMoLHYh/5q
    r9Sbknfu7dmRvF4V8k2j+voUrz0F9vLnUCbceDvi5cR4ehflGUW9/Gp5BBsb8NvR
    DqBrgjf/nHmMM4V2GebyIFYDJvz/jIeSoy9E1apxD0u/F+n0YlveXpxpESZr3+pK
    zGyc9woawcUWcm9CZJjaZxu8/IFUfwIDAQABAoICAQCqayUTFA4rjqNHT3XIy631
    4uuNJZpf6Z7zY3ZXs+xyPH3rvdqqtQfESp7eJopm9M56c8tJoU7HcJUZDOEhl+GO
    sIdvgDzDPB2+DlVICSxlwxLF2P5ovD4QB28zfZPemnnppWfiQQJEwrxbh3jKFb/+
    gCcJX/jq2UrwN0xc3W6FB35j87pXyNfv424c2WG5vx/Vc3eWXUdF5rNgsTxasnO8
    hY93FkB+RgjAouXPCrEbuO4B6RLCiz123TheT2Y3UWJ6lKQsqk+aF1Kh0tEoVyLh
    y7hSv1O9XsmuGeE+A5ZGIcIBg0Rj8PfHw9qmTdyg3e2pwriWkMcD7n5ITOVX1SDt
    +Kfo6xNDqkZg1L1iZeWexasLC5Gpp99Bb+pbvoNudWHGMuicqXphjJTSVKMxoE4S
    7A6UyBzTHRr5lMX2OeKtxSH0+RrlCKWVDoLREJ/7U2gdI/M/WthsC5WbGl4UWRvy
    Azxf4Mon4oSYG9I1QPkkmhSbuN3K3Ca+J631/N7AbvOunhD41IiXvmypR5x4nbQl
    Si6n5aqQqvTHeuXiAUUsKlGuw4oZ6bGVJ9hHoPHo4kWpbdvAI46lPVIaSEn7FW9i
    4zarZTTS1jS8mYFBSxVuLlRxKQov2wV/RchAW7BTVJ+nXt40mSeC6EjAjOoPi7hz
    14ug0dSW1DT9R7LGHUAaoQKCAQEA7URM/hzaD7pl1FjwJQj54rudMtk1oAYLzEv7
    as5ZsrItHEPspgc5R1qlUv0xNI/8Rp2T/NgxTGGgJMdAfJWVj7B+soAp4ld9nqSW
    cLHY/NzkxW3KZnRQW5U73a7zYznIvpl+ALEjHlE3Gn/gEFn6TjHj1VIKfQW7I+q3
    +N0bRL89Bb5B3gQiZ1YPoOeWspbkFuFS2aKxL0Fv4FavAob29VjXWyRCTKkXWweD
    6X2ThkwVTQc6yauWv/Uhs/2DAJM3QDN4oe0kdOrkSuWKqv8K/TWG+Ww+2gM85v96
    Q+jqaegYAMBs/chUZFoFT7AX2iM5MVMqt+A0eLL0mZdCJD5ICQKCAQEA5Ufdki9X
    aQsIFE3kQcpIBPZsX6tgubt0owyBDPQlCatgWSyG3LaLf2wqP/mEhbPlyMskJmg2
    0QlNXhUrINkyYMS6Qqyff9ko0wf5zqKYCXntOWldQmOjQAhySKO9VTFKJMA7r4uh
    5O2IXqw302/sTeLLuGCdOwF398gOFqLv9ekG0JBcbKcz4wy3HYKhNQleKH9hiPhx
    VLd/fvrkWVssDGpuJw7ykRBmPdwpCXglWKZFqfSx+Mh1FpoZKmUDVnJyNl8Kju85
    RBO45TiyLCznXHJcafeVtHlqrM5FI+HK6IyTuidKPFwYKmNoPzmPp4ZudRBbUlYL
    EDS4N+pKWdMKRwKCAQAjCpZQZVRzRDUr0mLNJXE6YjkKPHgmBR6S8pnUIVuv/46Y
    ARQfRSvZdPK7ufcdazJ3/2fOzOMjA7wSEndcrv7itM9Rb4pACmncFzS8uhdw6PLE
    kb11ujHwBK9Nwzvg6LTUKXkpgv/Lx3Ta7g3afF9yUv3yEGbKJiGIYW8ASy9uzMun
    YHz73CJ0noo6WlmwUIapNmf1CokekIyEVmkMd4Bbpd5QcJ92EPcJE6gQwOIb0HrI
    4It3I2dlPD/ZBFTnrdZYHgHv8EUVG2fSA+qh7H7j/JbNmYYCzr2c5BhblTehooyA
    9+pg5MhJ9d2Y8knjhpY4ya6ib3NwbAWh9WvoTGZ5AoIBAQDW1d/nejSNWKjZXaLj
    goa5H62sdwjK/7rqjGzflmSeCtbct7wmU2Win9d22nYyUb6dxrq4wi2a8Pxti6g9
    v0ZVJgDhOJ67TN/T3UVVOUT8nCKMCQ45huMQvNlY9xQRH345sWY7trqbp3aAPx6Q
    H+9ri3cX7G9nOpkOs4V/8GyoHxEjnCD+Li2QMfnizOQAriZsC+94SFLo7oeok64j
    jCpZ99/++SKQiq1CiWhqVwmnZyUfewjH9AzCgOHTt5LJDbO2/pcGF2GxSEmXfuh0
    PB8NoJq3MCY2VQ5/nUdrt8ZI4HALnYURybla/opPs7/HWU9moUzweW8kYEG9IutH
    /1dBAoIBADI/7f3CRu50vggP3ya2SvPnxdhOYNyM7NANABSN7Osxzo7bVYvbz7JR
    FtRS0OrjH7wF7Ak41rXASB3HoRZuigf4SoR3Wjspu9o2TvAZ3U/2wusDrb4nu0hk
    kQ83fHTtxFK3KRJjy79Wy0+VT55hoQzCs051lRi93B8gzdl3I7wUJEBW5BUSvtVD
    gNAgiG7KJNGoK2dau3YKyvHGSfaqJfDWtqvDqUdRCe4rkmA2vPff8pJSEbupS2Ri
    MMJ1LWTk2jw6HVmKsFYFVSsl5ihP1U0xpj2aOBE3wI4qpu9HTO167zrEbzXP8N0G
    zFI3DtQwDM1HRD70NEHKKcLr99Jkd84=
    -----END PRIVATE KEY-----