apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-cert-config
  namespace: media
data:
  client.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGojCCBIqgAwIBAgIEDbZl9zANBgkqhkiG9w0BAQsFADB7MQswCQYDVQQGEwJS
    TzESMBAGA1UEBxMJQnVjaGFyZXN0MRgwFgYDVQQKEw9DeWJlckdob3N0IFMuQS4x
    GzAZBgNVBAMTEkN5YmVyR2hvc3QgUm9vdCBDQTEhMB8GCSqGSIb3DQEJARYSaW5m
    b0BjeWJlcmdob3N0LnJvMB4XDTI1MTIxMzIwNDI0NloXDTM1MTIxMTIwNDI0Nlow
    czELMAkGA1UEBhMCUk8xEjAQBgNVBAcMCUJ1Y2hhcmVzdDEYMBYGA1UECgwPQ3li
    ZXJHaG9zdCBTLkEuMRMwEQYDVQQDDApYemVFSDZKS1l0MSEwHwYJKoZIhvcNAQkB
    FhJpbmZvQGN5YmVyZ2hvc3Qucm8wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQCtJn9LK1G1Ng/wHxOhOLL6wtoKYsXs7ym7pdQid0Dv4PEZuVsX49x3cyk2
    4WivShe9u/pn5MNg0u+GaA4pmxPlcAI58EHIIQL6G7JoAOB4Xvz6NQNJjZDhkDKv
    pfBT0f/upm0IikEQZWm3RmhKJmbmG60vbtOsdDYWcDvcvjrQKdhDmFUnSsZ7PS/W
    rlYi/5488Zhu+DDQ+SmNxksj59VUVjGNDTZRsoanEfN5tj8oWGp/+cqh7HQCwdDR
    gIoWr022qZ5fLwVz0lXVNsEaILUdrCblk7kLidGncljKW+0cZWXXAXPL4VWMtnto
    1JtPY581tYtzJMNhjx/tif8k5z0PxotSXv+AMi3aFRlt08HAgaNWXPMetfqiJxEn
    vmw1p76bS6Y5yJnQHOmpVrFVMpFVHX80d/HZbpIj8+NoJ727YAzcvptTdJ3WEw+L
    J/mRNXmxZvSdgUcQfnhTMBLjODucRFvvaYrZYH9B7ZWR73iAQOAxbDJAZHMfYN55
    D4C9XzNhJ4Ln4s/67f3wjz1qBbk4HXPTg8dhwvbTWhp734aO9uzmRsyRNgTHi0oU
    XsTnRljhNmwiYfTMSlQ6SLKT8RSGjvytqfM25x/vDN0bCI6JUvhjxnRTeJKo1fba
    5AkfD2NA52fB3MPmUvFSgQ3/TaU8hjVd/OKrLIYGe50CyotlcwIDAQABo4IBNDCC
    ATAwCQYDVR0TBAIwADALBgNVHQ8EBAMCBaAwNAYJYIZIAYb4QgENBCcWJUN5YmVy
    R2hvc3QgR2VuZXJhdGVkIFVzZXIgQ2VydGlmaWNhdGUwEQYJYIZIAYb4QgEBBAQD
    AgeAMB0GA1UdDgQWBBSBIDOCIheuaKRtA5j5qxraZO0eoTCBrQYDVR0jBIGlMIGi
    gBTq10rWD8d7mrON4Cgzl4e3iKf2JaF/pH0wezELMAkGA1UEBhMCUk8xEjAQBgNV
    BAcTCUJ1Y2hhcmVzdDEYMBYGA1UEChMPQ3liZXJHaG9zdCBTLkEuMRswGQYDVQQD
    ExJDeWJlckdob3N0IFJvb3QgQ0ExITAfBgkqhkiG9w0BCQEWEmluZm9AY3liZXJn
    aG9zdC5yb4IJAJxUG61mxDS7MA0GCSqGSIb3DQEBCwUAA4ICAQBQ0UMK5t8uaTrm
    2Ti0u7WerLEKMBT6C7rje5SwvGNevkflSZU+n4zHUyhiCIs8w2dFGV8u1RkLZNV/
    CP/4p8+G4GwlZtWNacOplvOcUO2LXhQYa2cUh1vCHfO0W/+yLXoRMv+kENOIeUyQ
    B+3QJBFDc/ovbUbWaAi1L2iExE8qYII1v3pQ9hI7enyiGHeOter8zFLk+46Emigk
    iqyhdcjzFWmMCYdYoZIdqLLpykde4z7LiiXXswH0LaVzyKb0rbMD8Af+3jzfc/67
    RrGZvrXVS1VDe0llLWl1wZcA/6TI2sXtKXl2kK9ajO1iXC80LMW3dHC+b0FEN3CW
    +H0DO2eidc+seaZIWWs6rDwShBNBn4U9WzVnsz0l2BjFwSiI06qdkG6pa3FJ6q4m
    rcNwY2rLMpTwB05UK9PVFN2Np4Vitmhq0jFGZAnccEs/8LXKkVrMqSAla/kmjzwC
    +ePAOwgaCjNZYN5CjtpaZUppogO5dulugGWn0DiAXz4SxMUC7Q6JiEMArrzYLQrX
    ZCACXX4OGNlP4JOlayPv68DT2t5TeOc1XHPJTEBkdDgLZwFGdATK9/Vj7aUDCoOe
    6viERaykctWt20uOoT5l2MLL5189C75QZOWLw3vs9PbPw0lz/QwOyVrZfDThnL7p
    jsnx5XmcHTWP7xEvHqnjz53Y5kN1oA==
    -----END CERTIFICATE-----
  client.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCtJn9LK1G1Ng/w
    HxOhOLL6wtoKYsXs7ym7pdQid0Dv4PEZuVsX49x3cyk24WivShe9u/pn5MNg0u+G
    aA4pmxPlcAI58EHIIQL6G7JoAOB4Xvz6NQNJjZDhkDKvpfBT0f/upm0IikEQZWm3
    RmhKJmbmG60vbtOsdDYWcDvcvjrQKdhDmFUnSsZ7PS/WrlYi/5488Zhu+DDQ+SmN
    xksj59VUVjGNDTZRsoanEfN5tj8oWGp/+cqh7HQCwdDRgIoWr022qZ5fLwVz0lXV
    NsEaILUdrCblk7kLidGncljKW+0cZWXXAXPL4VWMtnto1JtPY581tYtzJMNhjx/t
    if8k5z0PxotSXv+AMi3aFRlt08HAgaNWXPMetfqiJxEnvmw1p76bS6Y5yJnQHOmp
    VrFVMpFVHX80d/HZbpIj8+NoJ727YAzcvptTdJ3WEw+LJ/mRNXmxZvSdgUcQfnhT
    MBLjODucRFvvaYrZYH9B7ZWR73iAQOAxbDJAZHMfYN55D4C9XzNhJ4Ln4s/67f3w
    jz1qBbk4HXPTg8dhwvbTWhp734aO9uzmRsyRNgTHi0oUXsTnRljhNmwiYfTMSlQ6
    SLKT8RSGjvytqfM25x/vDN0bCI6JUvhjxnRTeJKo1fba5AkfD2NA52fB3MPmUvFS
    gQ3/TaU8hjVd/OKrLIYGe50CyotlcwIDAQABAoICAA2qIBmajZQzdAaLLU1n4BgS
    EIsJSH1uUmjQqXEe4C0OH3jcO+giv19d4z7FgzFyM3VxxE02rISToPuGcret2WAd
    +s7/uvFESavbS7URfKWDOYu1a1D+rxReAOIDwnea9wuqbqhh4MieeD1SfSB871nx
    jTVVFbdiZHJY4SCGkrWi18Jd3zp+mDNZnNDgaUPR0HcWyeTYCWI0h6b8oyluPlOt
    ibOL+2FvKVk9/Wz5iPpyH9WBrRAiTPV6vjQKZNttckCcGjeAynldfBCbhZm+QwzY
    bSlpAw16DuWcDI3Lu2amSecx4iWQ3uN/8zVOsgMN5Z6jeSHZIOIuHWLtpQkQhqz6
    w19+2cCqfHJFSS541d4buGohvxouviB/lWQiPWi/QZIdgkFnBmzPN8JqdAaFCrGe
    Dm94qUrS+5keZPsoC2w5puHXBv3URIGnL+G5OsUMcP4ho0Yh/smdaFIOTSMopBnm
    SHvbYlMxcbEezUzjYMSeeoSZAQG2bBlLLXvW0KrTisMm8BdzEwythMNEESN/4dSq
    oazeqwcPq1ZoWdLQXDYXk2rJ9nkpO1zLN9I1DBQUJdewsEybTfJwD2A+Kqcu9o2Z
    zIWtwBf0DdVvAB8qfmPHW3uYr8nwWManztlqlfLbq3onelhE8fUfqN77W93ARSMI
    2LhIckBfYfJl+SLky6YhAoIBAQDd6rd1Xc4phmPPzrrhso8N1e+mJoTgPw1GZSbQ
    cbTkDheu7opXbnWtct/8D0EVBXJ6WCNToQFIcdQcFow+OhQ3S+m2Cz9ZKhYBl5Rs
    r3izuZl2a+sVU/cfA4c7K7X7VqYvTMytLgQesASLVGMs8ILkEGHNvdBMDMzJm72k
    2XjSaIpTi5TKjTl3aak/G6hPCGvmIiea9Ea1nJklQbLbqKwGrUU6MT83zlyYNF5x
    kLxL1SIYXY59yrsGnD3RSaicJc3Y/p9Tc7k/6lYO+rBr/fz86M0yXQ3KiC9n0v+8
    5VqVqgxks0kZICKhUkXkMW/yAnA9nfujrmP2lOPl3sySl+5fAoIBAQDHvmPC9kLA
    h/G67KqHuOwT2chp6xhCNyoTqNmMSyJ9FzPeO8xI/HAiBadja/q4UFtforwNHP8j
    oWVTPdWGlwrkfdsuI7xvSLEJRmvi3OQUKUvhas/b90az5t1yqoUOmf7frpvpZWrA
    FTN1vFjl46ipFI8ZIPMxQbVsW4eHVjV+EACFAYB5vug9r10/rcGpwWbSn+bkrAQm
    YNsv4rncHoHvLxQ17IoJ3jZazPpjSkl1LD5Mlb19FWPstjB2FBzyciiOr3rr5GGI
    CV9V6aKDV8+Q5nVO0ztgsNWqDmmiUgaGFMiofwb0oXvxE7ttAVS/FN/JS+T2rZrh
    FneGuAf90HltAoIBAQC4LouvXHi0XDbRDZproiA68nmhY8zatVoWN/O8AvOIZ+3e
    IVsub545o+Mkt6Bjiw7VXfuL+FAxSVArM8eYCeonbtj9X15naZe0IJNulUBPolYt
    RCprnDG5SttdD81NWkA5d7tUbKG8uog6/4IElWV9Vd9mvAh6ZhE9rwX6IQi3UU6l
    Qm7uocG1SzvOBe1uEuZCrcxDPkTFjMBKfLmut9J3BC41uxPmBF8zcBuGlALDyZQv
    ts6BttX9CYYBAupvFq0/USz5PU3eL2bXrdbo+neTjMBp8XN1ygvWVvgsVgsVtnns
    xiSANvym+brKRwHLUZzIdyuYUS/kQvTXH1CYxoJvAoIBABVLhAFGFenG1Iu0LZ4Y
    pfqbzlUUflqY3QCJkN/3Jq8laR85StdBKodGCQl9epZp4sP4aooPXFglHdNZFUmr
    Ers3e8WYg79thYpSmq/uEtbfbDqVE6IE4+HMLDHMYjEjU9vvFqo0aMQfvoO/185y
    jgmwqmzoaWUH91qdC37vPva4qAWGGndgVgw1hQCD+tCpUNgFui0I9cxNqTCawGvq
    SLoCT+pL1I+mxC68CbnKMriuRdoOYMxUGnojFlmQXWGvsAk+RiGeEJPbQ/G53dyY
    4QU2vKzxsjPlxnHB5ZsrmYxz7Myh9lDgYoFaNDIz4SAaDp28XKW77nYu2gFf32I8
    9qUCggEBALAmtIWfuHX7xexeE4kwUUMXQWOcr8/EXMk/2bq6rBEaR15HYJ7/l6vK
    Xih6K2S0+eVm21nhjQjx+D2cW9qbX5Wt0FuLrZv4tzfQrNRhAbDj1alWivjNVW+8
    aD9ujnTIDoONaR+JfpFruJstBCbbzeicEbmsb+iBlvj8qpyaONT1KRwhwH+yO4Br
    U0FDgPYGzVSS8bLzpBsnpABggoCuLPjPTrvT/Z0SGx3qgoXSy9pthjRu7ZO3geOs
    InvVFpmPKM5gyYqhKYg/ohafgFVXE0OFgpiPNqifBAlhR2jLSntg1rOnGJCpBP2w
    EFUjIIsqZyFtAVxJ+uIiEfoeGj2w3fo=
    -----END PRIVATE KEY-----