---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-db
  namespace: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  namespace: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi